<?php
/**
 * Created by PhpStorm.
 * User: Utente
 * Date: 15/01/2019
 * Time: 09:05
 */


require_once _PS_MODULE_DIR_."aggregatecombination/classes/AggregateCombinationGroup.php";
require_once _PS_MODULE_DIR_."aggregatecombination/classes/AggregateCombinationGroupAttributes.php";

class AdminAggregateCombinationController extends ModuleAdminController
{
    public function __construct()
    {
        $this->table = 'ag_group';
        $this->className = 'AggregateCombinationGroup';
        $this->lang = true;
        $this->deleted = false;
        $this->colorOnBackground = false;
        $this->bulk_actions = array('delete' => array('text' => $this->l('Delete selected'), 'confirm' => $this->l('Delete selected items?')));
        $this->context = Context::getContext();
        // définition de l'upload, chemin par défaut _PS_IMG_DIR_
        $this->ajax = true;

        $this->bootstrap = true;
        parent::__construct();
    }

    /**
     * Function used to render the list to display for this controller
     */
    public function renderList()
    {
        $this->table = 'ag_group';
        $this->list_id = 'ag_group';
        $this->identifier = 'id_ag_group';
        $this->className = 'AggregateCombinationGroup';
        $this->_defaultOrderBy = 'position';

        $this->addRowAction('edit');
        $this->addRowAction('delete');
        $this->addRowAction('details');
        $this->bulk_actions = array(
            'delete' => array(
                'text' => $this->trans('Delete selected'),
                'confirm' => $this->trans('Delete selected items?')
            )
        );
        $this->fields_list = array(
            'id_ag_group' => array(
                'title' => $this->trans('ID'),
                'align' => 'center',
                'width' => 25
            ),
            'name' => array(
                'title' => $this->trans('Name'),
                'width' => 'auto',
            ),
            'position' => array(
                'title' => $this->trans('Position'),
                'width' => 70,
                'align' => 'center',
                'position' => 'position',
                'filter_key' => 'a!position',
            ),
            'active' => array(
                'title' => $this->trans('Active'),
                'width' => 'auto',
            ),
        );

        $lists = parent::renderList();
        parent::initToolbar();
        return $lists;
    }



    public function renderForm()
    {
        $this->fields_form = array(
            'tinymce' => true,
            'legend' => array(
                'title' => $this->trans('Combination Group'),
                'image' => '../img/admin/cog.gif'
            ),
            'input' => array(
                array(
                    'type' => 'text',
                    'lang' => true,
                    'label' => $this->trans('Name:'),
                    'name' => 'name',
                    'size' => 40
                ),
                array(
                    'type' => 'switch',
                    'label' => $this->trans('Active'),
                    'name' => 'active',
                    'required' => false,
                    'class' => 't',
                    'is_bool' => true,
                    'values' => array(
                        array(
                            'id' => 'active_on',
                            'value' => 1,
                            'label' => $this->trans('Yes', array(), 'Admin.Global'),
                        ),
                        array(
                            'id' => 'active_off',
                            'value' => 0,
                            'label' => $this->trans('No', array(), 'Admin.Global'),
                        ),
                    ),
                )
            ),
            'submit' => array(
                'title' => $this->trans('Save'),
            )
        );
        if (!($obj = $this->loadObject(true))) {
            return;
        }
        /* Thumbnail
         * @todo Error, deletion of the image
        */

        return parent::renderForm();
    }


    public function initContent()
    {
        return parent::initContent(); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        parent::init();
    }

    public function setMedia()
    {
        parent::setMedia();

        // Create a link with the good path
        $link = new Link;
        $parameters = array("action" => "action_name");
        $ajax_link = $link->getModuleLink('aggregatecombination','ajax', $parameters);


        Media::addJsDef(array(
            "ajax_link" => $ajax_link,
            'ag_admin_url' => $this->context->link->getAdminLink('AdminAggregateCombination'),
            'ag_token' => Tools::getAdminTokenLite('AdminAggregateCombination'),
            'file' => __FILE__
        ));

        $this->context->controller->addJS(_PS_MODULE_DIR_.'aggregatecombination/views/js/aggregatecombintion.js');
        //$this->context->controller->addJS(_PS_MODULE_DIR_.$this->name.'/views/js/main.js');
        $this->context->controller->addCSS(_PS_MODULE_DIR_.'aggregatecombination/views/css/main.css');
    }

    public function ajaxProcessSaveGroup()
    {
        $idProduct = Tools::getValue('product', 0);
        $nome = Tools::getValue('group', $this->trans("Empty Group"));
        $arrayCombination = Tools::getValue('element', []);
        $id_ag_group = Tools::getValue('id_ag_group', []);



        if ($id_ag_group) {
            $outArrayCombination = [];
            foreach ($arrayCombination as $key => $arr) {
                if (is_array($arr)) {
                    $outArrayCombination[$key] = $arr;
                }
            }

            $errors = 0;
            foreach ($outArrayCombination as $id_attribue => $attributes) {
                foreach ($attributes as $id_value) {
                    $acGA = new AggregateCombinationGroupAttributes();
                    $acGA->id_ag_group = $id_ag_group;
                    $acGA->id_attribute = $id_attribue;
                    $acGA->id_value = $id_value;
                    if (!$acGA->save())
                        $errors++;
                }
            }

            if (!$errors)
                die(json_encode(array('status' => true, 'message' => "Group saved successfully", 'id_ag_group' => $id_ag_group, 'nome' => $nome)));
            else
                die(json_encode(array('status' => false, 'message' => "An error occourred during group saving")));
        }
    }

    public function ajaxProcessGenerateCombinations()
    {

        //Tools::dieObject(Tools::getValue('group', []));

        $idProduct = Tools::getValue('product', 0);
        $arrayGroup = Tools::getValue('group', []);

        $query = "SELECT * FROM " . _DB_PREFIX_ . "ag_group_attribute where id_ag_group IN (" . implode($arrayGroup, ',') . ")";
        $results = Db::getInstance()->executeS($query);

        //$this->jsonLog($query);
        //$this->jsonLog($results, false);

        //die();

        $combination = [];
        $outCombination = [];
        while ($results) {
            foreach ($results as $res) {
                if (!isset($combination[$res["id_attribute"]])) {
                    $combination[$res["id_attribute"]] = [];
                }
                $combination[$res["id_attribute"]][] = $res["id_value"];
            }
            $index = 1;
            $k = 1;
            foreach ($combination as $key => $arr) {
                $outCombination[$index] = [];
                foreach ($arr as $value) {
                    $outCombination[$index][$k] = $value;
                    $k++;
                }
                $index++;
            }
            break;
        }

        $outCombination = $this->get_combinations($outCombination);
        $errors = 0;
        if ($this->createCombination($idProduct, $outCombination)) {
            foreach ($arrayGroup as $group) {
                //AggregateCombinationGroupProducts::linkProduct($group, $idProduct);
                $acGP = new AggregateCombinationGroupProducts();
                $acGP->id_ag_group = $group;
                $acGP->id_product = $idProduct;
                if ($acGP->save())
                    $errors++;
            }
        }

        if (!$errors)
            die(json_encode(array('status' => true, 'message' => $this->l('Combinations generated successfully'), 'query' => $query)));
        else
            die(json_encode(array('status' => false, 'message' => $this->l('An error occourred during combinations generation'), 'query' => $query)));
    }

    public function ajaxProcessDeleteGroup()
    {

        $idProduct = Tools::getValue('product', 0);
        $idGroup = Tools::getValue('idGroup', 0);

        if (AggregateCombinationGroupProducts::deleteByGroupIdAndProductId($idGroup, $idProduct))
            die(json_encode(array('status' => true, 'message' => "Valore cancellato correttamente")));
        else
            die(json_encode(array('status' => false, 'message' => "Si è verificato un errore dutante la cancellazione del gruppo")));
    }

    private function get_combinations($arrays)
    {
        $result = array(array());
        foreach ($arrays as $property => $property_values) {
            $tmp = array();
            foreach ($result as $result_item) {
                foreach ($property_values as $property_key => $property_value) {
                    $tmp[] = $result_item + array($property_key => $property_value);
                }
            }
            $result = $tmp;
        }
        return $result;
    }


    private function createCombination($idProduct, $outArrayCombination)
    {


        //return false;

        if ($idProduct) {

            $product = new Product($idProduct, true, 1);

            //ini_set("memory_limit", "512M");
            //$this->jsonLog($outArrayCombination);

            //return false;

            foreach ($outArrayCombination as $combinations) {


                if (!count($combinations))
                    continue;


                //$this->jsonLog(count($combinations));
                //$this->jsonLog($combinations, true);
                //$this->jsonLog($combinations);


                //continue;


                if (!$exists = $product->productAttributeExists($combinations)) {

                    Tools::dieObject($exists);

                    $price = 0;
                    $weight = 0;
                    $ecotax = 0;
                    $unit_price_impact = "";
                    $quantity = 1;
                    $reference = "";
                    $supplier_reference = "";
                    $ean13 = "";
                    $default = false;

                    $idProductAttribute = $product->addProductAttribute((float)$price, (float)$weight, $unit_price_impact, (float)$ecotax, (int)$quantity, "", strval($reference), strval($supplier_reference), strval($ean13), $default, NULL, NULL, NULL, NULL);
                    $product->addAttributeCombinaison($idProductAttribute, $combinations);
                }
            }

            //ini_set("memory_limit", "128M");

        }

        return true;
    }

    function jsonLog($object, $die = false)
    {
        echo json_encode(array('object' => $object))."<br>";
        if ($die)
            die("END");
    }

    public function jsLog($object)
    {
        $output = "<script>";
        if (is_array($object))
            foreach ($object as $item) {
                $output .= "console.log(" . json_encode($item) . ");";
            }
        else
            $output .= "console.log(" . json_encode($object) . ");";

        echo $output . "</script>";
    }
}